version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/app/static
      - media_volume:/app/media
    environment:
      - DEBUG=1
      - USE_POSTGRES=1
      - POSTGRES_DB=uway_db
      - POSTGRES_USER=uway_user
      - POSTGRES_PASSWORD=uway_password
      - DB_HOST=db
      - DB_PORT=5432
      - DJANGO_SETTINGS_MODULE=api.settings
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=uway_db
      - POSTGRES_USER=uway_user
      - POSTGRES_PASSWORD=uway_password
    ports:
      - "5432:5432"

volumes:
  postgres_data:
  static_volume:
  media_volume:
