# Generated by Django 5.1.3 on 2025-07-28 04:37

from django.db import migrations

def full_roles(apps, schema_editor):
    role = apps.get_model('roles', 'Role')
    role.objects.create(
        name='Conductor',
        description='Crea rutas y vehículos.'
    )
    role.objects.create(
        name='Estudiante',
        description='Toma viajes.'
    )
    role.objects.create(
        name='Profesor',
        description='Toma viajes.'
    )
    role.objects.create(
        name='Funcionario',
        description='Toma viajes.'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(full_roles)
    ]
