# Generated by Django 5.1.3 on 2025-07-27 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universities', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='university',
            name='email',
        ),
        migrations.RemoveField(
            model_name='university',
            name='password',
        ),
    ]
